In [24]:
import pygame, pygame.sndarray
from math import sin, pi

In [25]:
pygame.mixer.pre_init(frequency=44100, size=-16, channels=1)
pygame.mixer.init(frequency=44100, size=-16, channels=1)
print(pygame.mixer.get_init())
pygame.mixer.set_num_channels(1)
print(pygame.mixer.get_init())

(44100, -16, 2)
(44100, -16, 2)


In [26]:
import numpy as np
arr = np.random.randint(-32768, 32767, size=44100*2).reshape((44100, 2))

arr


array([[-28332,  -9969],
       [ 22311,  28641],
       [  3166,  27733],
       ...,
       [-18933,  -8902],
       [ -2154, -16110],
       [ 12307,  -9942]])

In [27]:
sound = pygame.sndarray.make_sound(arr)
sound.play()

In [28]:
arr_light = np.random.randint(-1000, 1000, size=44100*2).reshape((44100, 2))
sound = pygame.sndarray.make_sound(arr_light)
sound.play()

In [38]:

form = np.repeat([5000,-5000],63) 
arr = np.tile(form,350)
print(arr)
arr = np.repeat(arr, 2).reshape((44100,2))
print(arr)
sound = pygame.sndarray.make_sound(arr)
sound.play()


[ 5000  5000  5000 ... -5000 -5000 -5000]
[[ 5000  5000]
 [ 5000  5000]
 [ 5000  5000]
 ...
 [-5000 -5000]
 [-5000 -5000]
 [-5000 -5000]]


In [30]:
def make_sinusoid(frequency,amplitude):
    def f(t):
        return amplitude * sin(2*pi*frequency*t)
    return f

In [31]:
def sample(f,start,end,count):
    mapf = np.vectorize(f)
    ts = np.arange(start,end,(end-start)/count)
    values = mapf(ts)
    return values.astype(np.int16)

In [40]:
sinusoid = make_sinusoid(441,8000)
arr = sample(sinusoid, 0, 1, 44100)
arr = np.repeat(arr, 2).reshape((44100,2))
sound = pygame.sndarray.make_sound(arr)
sound.play()

In [44]:
def sawtooth(t):
    return t%1
def modified_sawtooth(t):
    return 8000 * sawtooth(441*t)
arr = sample(modified_sawtooth,0,1,44100)
arr = np.repeat(arr, 2).reshape((44100,2))
sound = pygame.sndarray.make_sound(arr)
sound.play()
